In [1]:
from sympy import *
from sympy.abc import x
import numpy as np
import math
import matplotlib.pyplot as plt

# Zadanie 3.

In [35]:
A = np.array([[3, 0.5, 8, 1],
     [7, 5, 1, -3],
     [-6, 1.5, -4.5, 1],
     [2, 10, 5, -7]])

b = np.array([99.5, 38, -69.5, 42])
np.linalg.cond(A)

8.630199572122246

In [351]:
true_X = np.linalg.solve(A,b)

In [352]:
true_X

array([ 5.,  1., 10.,  4.])

### D1

In [38]:
D_1 =  np.array([[100, 0, 0,0],
     [0, 100, 0, 0],
     [0, 0, 100, 0],
     [0, 0, 0, 100]])

In [39]:
A_1 = D_1 @ A
np.linalg.cond(A_1)

8.630199572122248

In [40]:
b_1 = D_1 @ b

In [41]:
X = np.linalg.solve(A_1,b_1)
X

array([ 5.,  1., 10.,  4.])

### D2

In [42]:
D_2 =  np.array([[1, 0, 0,0],
     [0, 10**10, 0, 0],
     [0, 0, -1, 0],
     [0, 0, 0,  -10**10]])

In [43]:
A_2 = D_2 @ A
np.linalg.cond(A_2)

68557890996.31502

In [44]:
b_2 = D_2 @ b

In [45]:
X = np.linalg.solve(A_2,b_2)
X

array([ 5.,  1., 10.,  4.])

### D3

In [338]:
D_3 =  np.array([[10**19, 0, 0,0],
     [0, 1, 0, 0],
     [0, 0, -10**(-304), 0],
     [0, 0, 0,  1]])

In [339]:
A_3 = D_3 @ A
np.linalg.cond(A_3)

inf

In [340]:
b_3 = D_3 @ b

In [357]:
X = np.linalg.solve(A_3,b_3)
X

array([ 5.0119426 ,  0.9188308 , 10.01346073,  3.89707097])

In [360]:
np.absolute( (X-true_X) / true_X )

array([0.00238852, 0.0811692 , 0.00134607, 0.02573226])

In [342]:
res = A_3 @ X - b_3
res

array([0.00000000e+000, 7.10542736e-015, 3.56911709e-305, 0.00000000e+000])

In [343]:
r = 0
for a in res:
    r += abs(a)
r

7.105427357601002e-15

### D4

In [361]:
D_4 =  np.array([[10**19, 0, 0,0],
     [0, 10*(-10), 0, 0],
     [0, 0, -10**(-320), 0],
     [0, 0, 0,  10**19]])

In [362]:
A_4 = D_4 @ A
np.linalg.cond(A_4)

inf

In [363]:
b_4 = D_4 @ b

In [364]:
X = np.linalg.solve(A_4,b_4)
X

array([  7.23540524, -14.19317797,  12.51956692, -15.26616209])

In [365]:
np.absolute( (X-true_X) / true_X )

array([ 0.44708105, 15.19317797,  0.25195669,  4.81654052])

In [348]:
A_4 @ X

array([ 9.95000e+020, -3.80000e+003,  1.36305e-318,  4.20000e+020])

In [366]:
res = A_4 @ X - b_4
res

array([0.00000e+000, 0.00000e+000, 6.68056e-319, 0.00000e+000])

In [350]:
r = 0
for a in res:
    r += abs(a)
r

6.68056e-319

### D_5

In [277]:
D_5 =  np.array([[1.2, 0, 0,0],
     [0, 1.2, 0, 0],
     [0, 0, 1.5, 0],
     [0, 0, 0, 0.8]])

In [278]:
A_5 = D_5 @ A
np.linalg.cond(A_5)

7.468047148770744

In [279]:
b_5 = D_5 @ b

In [281]:
X = np.linalg.solve(A_5,b_5)
X

array([ 5.,  1., 10.,  4.])

# Badanie epsilon

Najmniejsza na moduł reprezentowana liczba

In [55]:
np.nextafter(0, 1)

5e-324

Najmniejsza liczba, której kwadrat jest niezerowy

In [54]:
np.float64(2**(-537))**2

5e-324

Znaleznienie największej liczby mniejszej od 1

In [34]:
np.nextafter( np.float64(1), np.float64(0)) == 1 - 2**(-53)

True